### PR TITLE
macos: Small improvements to the backend

### PR DESCRIPTION
**Pull request by SamoZ256**
The validation errors have been fixed, setting window parent is now supported, better error handling, and the window is in focus when the application starts.

### CODE REVIEW

**Comment by markbolhuis** [comment]
Make sure commit message lines don't exceed 72 chars.

**Comment by SamoZ256** [comment]
Already renamed it, is there something else I have to do?

**Comment by markbolhuis** [comment]
Please rebase against any new changes, and don't merge. Also see my review comments.

**Comment by SamoZ256** [comment]
And how am I supposed to keep my fork up to date without merging with yours? Sorry, I haven't worked with git that much before

**Comment by markbolhuis** [comment]
> And how am I supposed to keep my fork up to date without merging with yours? Sorry, I haven't worked with git that much before

You should just be able to do a git rebase against origin/main (assuming origin is this repo and not your fork)

**Comment by SamoZ256** [comment]
Is it Ok now?

**Pull request merged**
